use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CapabilityName {
    NodeCreate,
    NodeList,
    NodeInspect,
    NodeObserve,
    NodeSendInput,
    NodeInterrupt,
    NodeStop,
    NodeTerminate,
    NodeArchive,
    NodeAttachBrowser,
    NodeAttachNativeTarget,
    NodeRestart,
    NodeResume,
    RelationshipCreate,
    RelationshipRemove,
    RelationshipList,
    GraphGet,
    HarnessList,
    HarnessInspect,
    HarnessConfigure,
    HarnessCapabilities,
    HarnessLaunchContext,
    SubstrateList,
    SubstrateInspect,
    SubstrateHealth,
    SubstrateLaunchNode,
    SubstrateStopNode,
    SubstrateDiagnostics,
    WorkspaceListRecent,
    WorkspaceInspect,
    ContextCurrentSystemMap,
    ContextLaunchPacket,
    ArtifactListRefs,
    ArtifactAddRef,
    NotifyChannelsList,
    NotifySend,
    RemoteCommandReceive,
    RemoteCommandReply,
    DecisionRequest,
    DecisionResolve,
    ClientConfig,
    TokenIssue,
    TokenRevoke,
    BaseUrlInspect,
    AttachUrlIssue,
    ChannelList,
    ChannelInspect,
    ChannelCreate,
    ChannelUpdate,
    ChannelDelete,
    ChannelMessages,
    ChannelTest,
    ChannelInbound,
    HookList,
    HookCreate,
    HookInspect,
    HookUpdate,
    HookDelete,
    HookFirings,
    HookEvents,
    HookTest,
    RecipeList,
    RecipeSpawn,
    NodeFork,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct CapabilityDescriptor {
    pub name: CapabilityName,
    pub path: String,
    pub method: String,
    pub description: String,
    pub available: bool,
}
