// asylum cockpit — mock state

window.ASYLUM_DATA = (() => {
  const HARNESSES = [
    { id: 'codex', name: 'Codex', kind: 'cli', available: true,
      caps: ['launch', 'observe', 'send_input', 'browser_attach', 'native_attach', 'interrupt', 'stop', 'tool_calls', 'transcript_export', 'context_telemetry'] },
    { id: 'claude-code', name: 'Claude Code', kind: 'cli', available: true,
      caps: ['launch', 'observe', 'send_input', 'browser_attach', 'native_attach', 'interrupt', 'stop', 'tool_calls', 'transcript_export', 'context_telemetry', 'subagents', 'native_resume', 'permission_prompts'] },
    { id: 'hermes', name: 'Hermes', kind: 'browser', available: false,
      caps: ['launch', 'observe', 'send_input', 'browser_attach'] },
    { id: 'pi', name: 'Pi', kind: 'api', available: false,
      caps: ['launch', 'observe', 'send_input'] },
    { id: 'shell', name: 'shell / pty', kind: 'pty', available: false,
      caps: ['launch', 'observe', 'send_input', 'browser_attach', 'interrupt'] },
  ];

  const SUBSTRATES = [
    { id: 'local', name: 'local', host: 'macbook.local', healthy: true, capacity: 0.32, nodes: 3 },
    { id: 'loon-us-west', name: 'loon-us-west', host: 'loon.iad1.fc', healthy: true, capacity: 0.61, nodes: 4 },
    { id: 'loon-us-east', name: 'loon-us-east', host: 'loon.sfo3.fc', healthy: true, capacity: 0.18, nodes: 1 },
    { id: 'loon-eu', name: 'loon-eu', host: 'loon.fra1.fc', healthy: false, capacity: 0, nodes: 0, warning: 'unreachable (last seen 4m)' },
  ];

  const NODES = [
    {
      id: 'cc-7c2af',
      name: 'cc-7c2af',
      role: 'command-center',
      harness: 'codex',
      substrate: 'local',
      workspace: '~/src/asylum',
      state: 'running',
      duration: '14m 32s',
      preview: '> reviewing graph topology…',
      parent: null,
      tokensIn: 142_804,
      tokensOut: 18_220,
      ctx: 0.72,
      tools: 47,
      isCommandCenter: true,
    },
    {
      id: 'sup-3d1e',
      name: 'sup-3d1e',
      role: 'supervisor',
      harness: 'claude-code',
      substrate: 'loon-us-west',
      workspace: '~/work/refactor-router',
      state: 'running',
      duration: '8m 04s',
      preview: '> awaiting worker w-9a4 results',
      parent: 'cc-7c2af',
      edge: 'spawned_for',
      tokensIn: 84_212, tokensOut: 12_104, ctx: 0.41, tools: 18,
    },
    {
      id: 'w-9a4f1',
      name: 'w-9a4f1',
      role: 'worker',
      harness: 'codex',
      substrate: 'loon-us-west',
      workspace: '~/work/refactor-router',
      state: 'running',
      duration: '6m 22s',
      preview: '+ wrote src/router/match.ts (114 lines)',
      parent: 'sup-3d1e',
      edge: 'supervises',
      tokensIn: 31_202, tokensOut: 4_018, ctx: 0.28, tools: 9,
    },
    {
      id: 'w-2b0c8',
      name: 'w-2b0c8',
      role: 'worker',
      harness: 'claude-code',
      substrate: 'loon-us-west',
      workspace: '~/work/refactor-router',
      state: 'waiting',
      duration: '6m 22s',
      preview: '? approve write to package.json',
      parent: 'sup-3d1e',
      edge: 'supervises',
      tokensIn: 18_402, tokensOut: 2_120, ctx: 0.19, tools: 4,
      decision: {
        title: 'permission requested',
        body: 'write to ~/work/refactor-router/package.json (modify dependencies block, +2 deps)',
        actions: ['approve', 'deny', 'always allow in this workspace'],
      },
    },
    {
      id: 'w-1f3a',
      name: 'w-1f3a',
      role: 'evaluator',
      harness: 'claude-code',
      substrate: 'local',
      workspace: '~/src/asylum',
      state: 'idle',
      duration: '22m 11s',
      preview: '— idle (last activity 22m ago)',
      parent: 'cc-7c2af',
      edge: 'spawned_for',
      tokensIn: 12_801, tokensOut: 1_402, ctx: 0.09, tools: 2,
    },
    {
      id: 'w-4e7b',
      name: 'w-4e7b',
      role: 'worker',
      harness: 'codex',
      substrate: 'loon-us-east',
      workspace: '~/work/spec-grader',
      state: 'errored',
      duration: '1h 12m',
      preview: '! exit 137 (oom) — substrate reclaimed vm',
      parent: 'sup-3d1e',
      edge: 'supervises',
      tokensIn: 4_101, tokensOut: 802, ctx: 0.04, tools: 1,
    },
    {
      id: 'sup-aa01',
      name: 'sup-aa01',
      role: 'supervisor',
      harness: 'codex',
      substrate: 'local',
      workspace: '~/src/asylum',
      state: 'running',
      duration: '3m 50s',
      preview: '> drafting test plan for capability service',
      parent: 'cc-7c2af',
      edge: 'spawned_for',
      tokensIn: 22_400, tokensOut: 3_018, ctx: 0.18, tools: 6,
    },
    {
      id: 'asst-d2c9',
      name: 'asst-d2c9',
      role: 'assistant',
      harness: 'claude-code',
      substrate: 'local',
      workspace: '~/notes',
      state: 'idle',
      duration: '47m 02s',
      preview: '— idle',
      parent: null,
      tokensIn: 8_201, tokensOut: 1_002, ctx: 0.06, tools: 0,
    },
  ];

  const RECIPES = [
    { id: 'cc',     name: 'start a command center', sub: 'codex or claude code with asylum context' },
    { id: 'fan',   name: 'spawn worker fan-out',   sub: '1 supervisor + N workers, shared workspace' },
    { id: 'observe', name: 'observe and summarize',  sub: 'read-only inspector across the fleet' },
    { id: 'plan',   name: 'run a plan to completion', sub: 'plan → implement → verify' },
    { id: 'check',  name: 'checkpoint and hand off', sub: 'serialize state, hand to fresh node' },
    { id: 'parallel', name: 'parallel exploration',  sub: 'same prompt, different harnesses' },
  ];

  // recent log lines
  const LOGS = [
    { ts: '14:22:08', lvl: 'run',  src: 'cc-7c2af',   msg: 'tool_call: graph.get(scope=fleet) → 8 nodes' },
    { ts: '14:22:04', lvl: 'info', src: 'sup-3d1e',  msg: 'streamed 412 tokens (ctx 41%)' },
    { ts: '14:22:01', lvl: 'warn', src: 'w-2b0c8',   msg: 'permission requested: write package.json' },
    { ts: '14:21:58', lvl: 'info', src: 'asylum',    msg: 'ntfy outbound → push: "w-2b0c8 wants permission"' },
    { ts: '14:21:42', lvl: 'run',  src: 'w-9a4f1',   msg: 'apply_patch: src/router/match.ts +114 -0' },
    { ts: '14:21:35', lvl: 'dbg',  src: 'loon',      msg: 'health check loon-us-west ok (rtt 38ms)' },
    { ts: '14:21:09', lvl: 'err',  src: 'w-4e7b',    msg: 'process exited 137 (oom-killed by substrate)' },
    { ts: '14:21:08', lvl: 'warn', src: 'loon-east', msg: 'vm reclaimed: w-4e7b (memory pressure)' },
    { ts: '14:20:54', lvl: 'info', src: 'cc-7c2af',  msg: 'received remote_command via ntfy: "status?"' },
    { ts: '14:20:54', lvl: 'info', src: 'asylum',    msg: 'ntfy reply → "8 nodes / 4 running / 1 waiting"' },
    { ts: '14:20:30', lvl: 'run',  src: 'sup-aa01',  msg: 'spawned: w-1f3a (evaluator, local)' },
    { ts: '14:20:14', lvl: 'info', src: 'asylum',    msg: 'capability node.attach.browser issued for cc-7c2af (token …8e2)' },
    { ts: '14:19:47', lvl: 'info', src: 'sup-3d1e',  msg: 'transcript checkpoint flushed (1.2 MB)' },
    { ts: '14:19:11', lvl: 'run',  src: 'cc-7c2af',  msg: 'context.launch_packet built: 12 files, 4 docs' },
    { ts: '14:18:55', lvl: 'dbg',  src: 'asylum',    msg: 'token.issue scope=node:cc-7c2af ttl=3600' },
  ];

  const NTFY_TEMPLATES = [
    {
      from: 'sup-3d1e',
      channel: 'ntfy/asylum-aaron',
      subject: 'checkpoint reached',
      body: 'router refactor: 4/6 modules done, tests passing. ok to continue?',
      replies: ['continue', 'pause', 'attach'],
    },
    {
      from: 'w-2b0c8',
      channel: 'ntfy/asylum-aaron',
      subject: 'permission requested',
      body: 'write to package.json (add 2 deps). approve / deny / always.',
      replies: ['approve', 'deny', 'always'],
    },
    {
      from: 'cc-7c2af',
      channel: 'ntfy/asylum-aaron',
      subject: 'summary',
      body: 'fleet: 4 running · 1 waiting · 1 errored. w-4e7b oom on loon-east, will not retry without input.',
      replies: ['retry', 'investigate', 'ignore'],
    },
  ];

  // ── messaging channels: how nodes / asylum reach you when you're away,
  // and how remote commands come back in. ntfy is the only live one for now.
  const CHANNELS = [
    {
      id: 'ntfy-aaron',
      kind: 'ntfy',
      name: 'ntfy/asylum-aaron',
      label: 'personal · push',
      direction: 'duplex',     // asylum → you, and you → asylum (replies)
      status: 'connected',
      detail: 'self-hosted · ntfy.fidget.local · tls',
      subscribers: 1,
      msg24h: 47,
      lastAt: '14:21:58',
      live: true,
    },
    {
      id: 'ntfy-team',
      kind: 'ntfy',
      name: 'ntfy/asylum-team',
      label: 'team broadcast',
      direction: 'outbound',
      status: 'connected',
      detail: 'self-hosted · 3 subscribers',
      subscribers: 3,
      msg24h: 12,
      lastAt: '13:48:11',
      live: true,
    },
    {
      id: 'webhook-loon',
      kind: 'webhook',
      name: 'loon-events',
      label: 'substrate webhooks',
      direction: 'inbound',
      status: 'connected',
      detail: 'POST https://localhost:5173/webhook/loon · hmac signed',
      msg24h: 188,
      lastAt: '14:22:01',
      live: true,
    },
    {
      id: 'sms-twilio',
      kind: 'sms',
      name: 'sms via twilio',
      label: '+1 ••• ••• 4711',
      direction: 'duplex',
      status: 'future',
      detail: 'adapter not built · planned for v0.2',
      live: false,
    },
    {
      id: 'discord',
      kind: 'discord',
      name: 'discord/asylum',
      label: '#asylum-control',
      direction: 'duplex',
      status: 'future',
      detail: 'bot adapter scaffolded · oauth pending',
      live: false,
    },
    {
      id: 'slack',
      kind: 'slack',
      name: 'slack/control-plane',
      label: '#asylum',
      direction: 'duplex',
      status: 'future',
      detail: 'planned · slash-command + threads',
      live: false,
    },
    {
      id: 'email-relay',
      kind: 'email',
      name: 'email · digest',
      label: 'aaron@fidgetlabs.co',
      direction: 'outbound',
      status: 'future',
      detail: 'daily / weekly digest · planned',
      live: false,
    },
  ];

  const CHANNEL_MESSAGES = [
    { ts: '14:21:58', dir: 'out', channel: 'ntfy-aaron',  from: 'asylum',   subject: 'permission requested', body: 'w-2b0c8 wants to write package.json (add 2 deps). approve / deny / always.', replies: ['approve', 'deny', 'always'] },
    { ts: '14:20:54', dir: 'in',  channel: 'ntfy-aaron',  from: 'aaron',    subject: 'remote_command',       body: 'status?' },
    { ts: '14:20:54', dir: 'out', channel: 'ntfy-aaron',  from: 'cc-7c2af', subject: 're: status',           body: '8 nodes / 4 running / 1 waiting / 1 errored' },
    { ts: '14:21:09', dir: 'in',  channel: 'webhook-loon', from: 'loon-east', subject: 'vm.reclaimed',       body: 'w-4e7b reclaimed (memory pressure)' },
    { ts: '14:18:32', dir: 'out', channel: 'ntfy-team',   from: 'asylum',   subject: 'sup-3d1e checkpoint',  body: 'router refactor: 4/6 modules done, tests passing.' },
    { ts: '14:14:02', dir: 'out', channel: 'ntfy-aaron',  from: 'sup-3d1e', subject: 'awaiting input',       body: 'no responses for 4m, escalating to push.' },
    { ts: '13:58:14', dir: 'in',  channel: 'ntfy-aaron',  from: 'aaron',    subject: 'remote_command',       body: 'pause w-9a4f1' },
    { ts: '13:58:14', dir: 'out', channel: 'ntfy-aaron',  from: 'asylum',   subject: 're: pause',            body: 'paused. resume with `resume w-9a4f1`.' },
    { ts: '13:48:11', dir: 'out', channel: 'ntfy-team',   from: 'asylum',   subject: 'fleet snapshot',       body: '8 nodes alive across 3 substrates · loon-eu unreachable' },
    { ts: '13:21:09', dir: 'in',  channel: 'webhook-loon', from: 'loon-west', subject: 'vm.up',              body: 'sup-3d1e vm provisioned (rtt 38ms)' },
  ];

  // ── hooks: declarative event triggers. when EVENT (matching FILTER) → ACTIONS.
  // user-editable — these are the "if-this-then-that" of asylum.
  const HOOKS = [
    {
      id: 'hk-permission-push',
      name: 'permission requests → push me',
      enabled: true,
      event: 'node.permission_requested',
      filter: 'any',
      actions: [
        { kind: 'channel', target: 'ntfy-aaron', template: 'permission for {node.id}: {decision.title}' },
        { kind: 'pause_node', target: 'event.node' },
      ],
      fired24h: 3,
      lastAt: '14:21:58',
      lastResult: 'ok',
    },
    {
      id: 'hk-oom-respawn',
      name: 'oom → respawn elsewhere',
      enabled: true,
      event: 'node.exited',
      filter: 'reason == "oom"',
      actions: [
        { kind: 'spawn', target: 'recipe:fan' },
        { kind: 'channel', target: 'ntfy-aaron', template: 'respawned {node.id} on {substrate.next}' },
      ],
      fired24h: 1,
      lastAt: '14:21:09',
      lastResult: 'ok',
    },
    {
      id: 'hk-ctx-warn',
      name: 'high context → checkpoint',
      enabled: true,
      event: 'node.ctx_pressure',
      filter: 'ctx >= 0.80',
      actions: [
        { kind: 'tool', target: 'transcript.checkpoint' },
        { kind: 'channel', target: 'ntfy-aaron', template: '{node.id} at {ctx}% — checkpointed' },
      ],
      fired24h: 2,
      lastAt: '14:11:02',
      lastResult: 'ok',
    },
    {
      id: 'hk-idle-archive',
      name: 'idle > 1h → archive',
      enabled: false,
      event: 'node.idle',
      filter: 'duration > 3600',
      actions: [
        { kind: 'archive', target: 'event.node' },
      ],
      fired24h: 0,
      lastAt: '—',
      lastResult: '—',
    },
    {
      id: 'hk-cc-summary',
      name: 'every 30m → cc summary push',
      enabled: true,
      event: 'schedule.30m',
      filter: 'any',
      actions: [
        { kind: 'tool', target: 'graph.get(scope=fleet)' },
        { kind: 'channel', target: 'ntfy-aaron', template: 'fleet: {summary}' },
      ],
      fired24h: 47,
      lastAt: '14:18:32',
      lastResult: 'ok',
    },
    {
      id: 'hk-error-investigate',
      name: 'worker errored → spawn investigator',
      enabled: false,
      event: 'node.errored',
      filter: 'role == "worker"',
      actions: [
        { kind: 'spawn', target: 'recipe:observe' },
      ],
      fired24h: 0,
      lastAt: '—',
      lastResult: '—',
      future: true,
    },
  ];

  const HOOK_FIRINGS = [
    { ts: '14:21:58', hook: 'hk-permission-push',  trigger: 'w-2b0c8.permission_requested',  outcome: 'pushed via ntfy-aaron · paused w-2b0c8',  ok: true },
    { ts: '14:21:09', hook: 'hk-oom-respawn',      trigger: 'w-4e7b.exited(oom)',             outcome: 'spawned w-c014 on loon-us-west · pushed',   ok: true },
    { ts: '14:18:32', hook: 'hk-cc-summary',       trigger: 'schedule.30m',                   outcome: 'graph.get → ntfy-aaron',                    ok: true },
    { ts: '14:11:02', hook: 'hk-ctx-warn',         trigger: 'cc-7c2af.ctx 0.72→0.81',          outcome: 'transcript.checkpoint(1.2MB) · pushed',     ok: true },
    { ts: '13:48:32', hook: 'hk-cc-summary',       trigger: 'schedule.30m',                   outcome: 'graph.get → ntfy-aaron',                    ok: true },
    { ts: '13:39:14', hook: 'hk-permission-push',  trigger: 'w-1f3a.permission_requested',    outcome: 'pushed · approved within 14s',              ok: true },
    { ts: '13:18:32', hook: 'hk-cc-summary',       trigger: 'schedule.30m',                   outcome: 'graph.get → ntfy-aaron',                    ok: true },
    { ts: '12:48:32', hook: 'hk-cc-summary',       trigger: 'schedule.30m',                   outcome: 'graph.get → ntfy-aaron',                    ok: true },
    { ts: '11:02:11', hook: 'hk-ctx-warn',         trigger: 'sup-3d1e.ctx 0.78→0.82',          outcome: 'transcript.checkpoint(0.9MB)',              ok: true },
  ];

  const EVENT_CATALOG = [
    { id: 'node.permission_requested', label: 'node requests a permission' },
    { id: 'node.exited',                label: 'node exits' },
    { id: 'node.errored',               label: 'node enters errored state' },
    { id: 'node.idle',                  label: 'node idle threshold reached' },
    { id: 'node.ctx_pressure',          label: 'context window pressure' },
    { id: 'node.tool_call',             label: 'specific tool call observed' },
    { id: 'graph.spawn',                label: 'new node spawned' },
    { id: 'substrate.unreachable',      label: 'substrate health degraded' },
    { id: 'channel.inbound',            label: 'inbound message on channel' },
    { id: 'schedule.5m',                label: 'every 5 minutes' },
    { id: 'schedule.30m',               label: 'every 30 minutes' },
    { id: 'schedule.cron',              label: 'cron expression…' },
  ];

  return { HARNESSES, SUBSTRATES, NODES, RECIPES, LOGS, NTFY_TEMPLATES, CHANNELS, CHANNEL_MESSAGES, HOOKS, HOOK_FIRINGS, EVENT_CATALOG };
})();
