[alias]
run-asylum-dev = "run -p xtask -- run-asylum-dev"
run-daemon-dev = "run -p xtask -- run-daemon-dev"
run-cockpit-dev = "run -p xtask -- run-cockpit-dev"
run-asylum = "run -p xtask -- run-asylum"
run-daemon = "run -p xtask -- run-daemon"
build-asylum = "run -p xtask -- build-asylum"
build-rust = "run -p xtask -- build-rust"
build-cockpit = "run -p xtask -- build-cockpit"
build-asylum-release = "run -p xtask -- build-asylum-release"
test-asylum = "run -p xtask -- test-asylum"
test-rust = "run -p xtask -- test-rust"
test-cockpit = "run -p xtask -- test-cockpit"
test-asylum-release = "run -p xtask -- test-asylum-release"
check-asylum = "run -p xtask -- check-asylum"
status-asylum-dev = "run -p xtask -- status-asylum-dev"
stop-asylum-dev = "run -p xtask -- stop-asylum-dev"
reset-asylum-dev = "run -p xtask -- reset-asylum-dev"
publish-asylum-release = "run -p xtask -- publish-asylum-release"
